//! Reference values generated by scripts/verify_pynite.py from the pinned
//! Pynite implementation. These tests need no Python installation.
use oa_core::*;
use serde::Deserialize;

#[derive(Deserialize)]
struct Reference {
    cases: Vec<Fixture>,
}
#[derive(Deserialize)]
struct Fixture {
    name: String,
    request: AnalysisRequest,
    relative_tolerance: f64,
    expected: Vec<Expected>,
}
#[derive(Deserialize)]
struct Expected {
    combination: String,
    displacements: Vec<[f64; 6]>,
    reactions: Vec<[f64; 6]>,
    frame_end_forces: Vec<[f64; 12]>,
}
#[test]
fn pynite_differential_acceptance() {
    let reference: Reference =
        serde_json::from_str(include_str!("fixtures/pynite_reference.json")).unwrap();
    assert!(reference.cases.len() >= 24);
    for fixture in reference.cases {
        let AnalysisResponse::Static { combinations, .. } =
            solve(&fixture.request).unwrap_or_else(|e| panic!("{}: {e}", fixture.name))
        else {
            panic!("expected static fixture")
        };
        assert_eq!(combinations.len(), fixture.expected.len());
        for (actual, expected) in combinations.iter().zip(&fixture.expected) {
            assert_eq!(actual.combination, expected.combination);
            for (field, a, b, atol) in [
                (
                    "displacements",
                    actual.displacements.as_ref().unwrap(),
                    &expected.displacements,
                    1e-10,
                ),
                (
                    "reactions",
                    actual.reactions.as_ref().unwrap(),
                    &expected.reactions,
                    1e-4,
                ),
            ] {
                for (i, (a, b)) in a.iter().flatten().zip(b.iter().flatten()).enumerate() {
                    assert!(
                        (a - b).abs() <= atol + fixture.relative_tolerance * b.abs(),
                        "{} / {} / {field} / {i}: {a:e} vs {b:e}",
                        fixture.name,
                        actual.combination
                    );
                }
            }
            for (i, (a, b)) in actual
                .frames
                .as_ref()
                .unwrap()
                .iter()
                .zip(&expected.frame_end_forces)
                .enumerate()
            {
                for (j, (actual_force, expected_force)) in
                    a.local_end_forces.iter().zip(b).enumerate()
                {
                    assert!(
                        (actual_force - expected_force).abs()
                            <= 1e-4 + fixture.relative_tolerance * expected_force.abs(),
                        "{} / {} / frame {i} DOF {j}",
                        fixture.name,
                        actual.combination
                    );
                }
            }
        }
    }
}
